# Generated by Django 6.1.1 on 2026-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
